services:
  django:
    build:
      context: ./django/
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.envs/dev.env